version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_db
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - my_network
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jorge
      MYSQL_PASSWORD: jorgecontrasena

networks:
  my_network:

volumes:
  mysql_data:


