version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: jorge
      MONGO_INITDB_ROOT_PASSWORD: jorge

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jorge
      ME_CONFIG_MONGODB_ADMINPASSWORD: jorge
      ME_CONFIG_BASICAUTH_USERNAME: jorge
      ME_CONFIG_BASICAUTH_PASSWORD: jorge
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  my-network:

volumes:
  mongo-data:



  




