version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jorge
      MYSQL_PASSWORD: jorgecontrasena

networks:
  my-network:

volumes:
  mongo-data:


